using Avalonia.Styling;
using Avalonia.Themes.Fluent;

namespace Andromeda.Tools.Avalonia.Themes.ViewModels
{
    internal class FluentViewModel : ThemePreview
    {
        public FluentViewModel(ThemeVariant themeVariant) :
            base(themeVariant)
        {
        }

        protected override Styles Theme => _theme;

        protected override string[] ColorsList => _colors;

        protected override string[] BrushesList => _brushes;

        private static readonly Styles _theme = new FluentTheme();

        private static readonly string[] _colors = [
            "SystemAccentColor",
            "SystemAccentColorDark1",
            "SystemAccentColorDark2",
            "SystemAccentColorDark3",
            "SystemAccentColorLight1",
            "SystemAccentColorLight2",
            "SystemAccentColorLight3",
            "SystemAltHighColor",
            "SystemAltLowColor",
            "SystemAltMediumColor",
            "SystemAltMediumHighColor",
            "SystemAltMediumLowColor",
            "SystemBaseHighColor",
            "SystemBaseLowColor",
            "SystemBaseMediumColor",
            "SystemBaseMediumHighColor",
            "SystemBaseMediumLowColor",
            "SystemChromeAltLowColor",
            "SystemChromeBlackHighColor",
            "SystemChromeBlackLowColor",
            "SystemChromeBlackMediumColor",
            "SystemChromeBlackMediumLowColor",
            "SystemChromeDisabledHighColor",
            "SystemChromeDisabledLowColor",
            "SystemChromeGrayColor",
            "SystemChromeHighColor",
            "SystemChromeLowColor",
            "SystemChromeMediumColor",
            "SystemChromeMediumLowColor",
            "SystemChromeWhiteColor",
            "SystemChromeGrayColor",
            "SystemErrorTextColor",
            "SystemListLowColor",
            "SystemListMediumColor",
            "SystemRegionColor",
            "SystemRevealListLowColor",
            "SystemRevealListMediumColor",
        ];

        private static readonly string[] _brushes = [
            "SystemControlTransparentBrush",
            "SystemControlBackgroundAccentBrush",
            "SystemControlBackgroundAltHighBrush",
            "SystemControlBackgroundAltMediumHighBrush",
            "SystemControlBackgroundAltMediumBrush",
            "SystemControlBackgroundAltMediumLowBrush",
            "SystemControlBackgroundBaseHighBrush",
            "SystemControlBackgroundBaseLowBrush",
            "SystemControlBackgroundBaseMediumBrush",
            "SystemControlBackgroundBaseMediumHighBrush",
            "SystemControlBackgroundBaseMediumLowBrush",
            "SystemControlBackgroundChromeBlackHighBrush",
            "SystemControlBackgroundChromeBlackMediumBrush",
            "SystemControlBackgroundChromeBlackLowBrush",
            "SystemControlBackgroundChromeBlackMediumLowBrush",
            "SystemControlBackgroundChromeMediumBrush",
            "SystemControlBackgroundChromeMediumLowBrush",
            "SystemControlBackgroundChromeWhiteBrush",
            "SystemControlBackgroundListLowBrush",
            "SystemControlBackgroundListMediumBrush",
            "SystemControlDisabledAccentBrush",
            "SystemControlDisabledBaseHighBrush",
            "SystemControlDisabledBaseLowBrush",
            "SystemControlDisabledBaseMediumLowBrush",
            "SystemControlDisabledChromeDisabledHighBrush",
            "SystemControlDisabledChromeDisabledLowBrush",
            "SystemControlDisabledChromeHighBrush",
            "SystemControlDisabledChromeMediumLowBrush",
            "SystemControlDisabledListMediumBrush",
            "SystemControlDisabledTransparentBrush",
            "SystemControlFocusVisualPrimaryBrush",
            "SystemControlFocusVisualSecondaryBrush",
            "SystemControlRevealFocusVisualBrush",
            "SystemControlForegroundAccentBrush",
            "SystemControlForegroundAltHighBrush",
            "SystemControlForegroundAltMediumHighBrush",
            "SystemControlForegroundBaseHighBrush",
            "SystemControlForegroundBaseLowBrush",
            "SystemControlForegroundBaseMediumBrush",
            "SystemControlForegroundBaseMediumHighBrush",
            "SystemControlForegroundBaseMediumLowBrush",
            "SystemControlForegroundChromeBlackHighBrush",
            "SystemControlForegroundChromeHighBrush",
            "SystemControlForegroundChromeMediumBrush",
            "SystemControlForegroundChromeDisabledLowBrush",
            "SystemControlForegroundChromeWhiteBrush",
            "SystemControlForegroundChromeBlackMediumBrush",
            "SystemControlForegroundChromeBlackMediumLowBrush",
            "SystemControlForegroundChromeGrayBrush",
            "SystemControlForegroundListLowBrush",
            "SystemControlForegroundListMediumBrush",
            "SystemControlForegroundTransparentBrush",
            "SystemControlHighlightAccentBrush",
            "SystemControlHighlightAltAccentBrush",
            "SystemControlHighlightAltAltHighBrush",
            "SystemControlHighlightAltBaseHighBrush",
            "SystemControlHighlightAltBaseLowBrush",
            "SystemControlHighlightAltBaseMediumBrush",
            "SystemControlHighlightAltBaseMediumHighBrush",
            "SystemControlHighlightAltAltMediumHighBrush",
            "SystemControlHighlightAltBaseMediumLowBrush",
            "SystemControlHighlightAltListAccentHighBrush",
            "SystemControlHighlightAltListAccentLowBrush",
            "SystemControlHighlightAltListAccentMediumBrush",
            "SystemControlHighlightAltChromeWhiteBrush",
            "SystemControlHighlightAltTransparentBrush",
            "SystemControlHighlightBaseHighBrush",
            "SystemControlHighlightBaseLowBrush",
            "SystemControlHighlightBaseMediumBrush",
            "SystemControlHighlightBaseMediumHighBrush",
            "SystemControlHighlightBaseMediumLowBrush",
            "SystemControlHighlightChromeAltLowBrush",
            "SystemControlHighlightChromeHighBrush",
            "SystemControlHighlightListAccentHighBrush",
            "SystemControlHighlightListAccentLowBrush",
            "SystemControlHighlightListAccentMediumBrush",
            "SystemControlHighlightListMediumBrush",
            "SystemControlHighlightListLowBrush",
            "SystemControlHighlightChromeWhiteBrush",
            "SystemControlHighlightTransparentBrush",
            "SystemControlHyperlinkTextBrush",
            "SystemControlHyperlinkBaseHighBrush",
            "SystemControlHyperlinkBaseMediumBrush",
            "SystemControlHyperlinkBaseMediumHighBrush",
            "SystemControlPageBackgroundAltMediumBrush",
            "SystemControlPageBackgroundAltHighBrush",
            "SystemControlPageBackgroundMediumAltMediumBrush",
            "SystemControlPageBackgroundBaseLowBrush",
            "SystemControlPageBackgroundBaseMediumBrush",
            "SystemControlPageBackgroundListLowBrush",
            "SystemControlPageBackgroundChromeLowBrush",
            "SystemControlPageBackgroundChromeMediumLowBrush",
            "SystemControlPageBackgroundTransparentBrush",
            "SystemControlPageTextBaseHighBrush",
            "SystemControlPageTextBaseMediumBrush",
            "SystemControlPageTextChromeBlackMediumLowBrush",
            "SystemControlErrorTextForegroundBrush",
            "SystemControlTransientBorderBrush",
            "SystemControlHighlightListLowRevealBackgroundBrush",
            "SystemControlHighlightListMediumRevealBackgroundBrush",
            "SystemControlHighlightAccentRevealBackgroundBrush",
            "SystemControlHighlightAccent3RevealBackgroundBrush",
            "SystemControlHighlightAccent2RevealBackgroundBrush",
            "SystemControlBackgroundChromeWhiteRevealBorderBrush",
            "SystemControlHighlightAltTransparentRevealBorderBrush",
            "SystemControlBackgroundTransparentRevealBorderBrush",
            "SystemControlTransientBackgroundBrush",
            "SystemControlDescriptionTextForegroundBrush",
            "SystemControlTransparentRevealBackgroundBrush",
            "SystemControlTransparentRevealBorderBrush",
            "SystemRegionBrush",
        ];
    }
}
